# PlayerTracker config

# Enable to allow players to execute /track command on players that are not currently in the same dimension (Note it will point to the portal they went through)
multiDimensional_tracking: false

# Enable to allow compass to point the location player was before they left (if disabled the compass will start spinning in circles when player leaves to protect them form spawn camping)
logoff_tracking: false

# Enable to allow player's compass to track portals (if disabled the compass will spin in circles when target changes dimensions)
portal_tracking: true

# Enable this to allow players to track with compass in inventory (don't know why anybody would need this but)
noCompass_tracking: false

# Enable this to allow players to get compass in inventory if they don't have it
giveCompass: false

# Change this if you feel like lodestone compass is shaking and upating too much (in ticks)
lodestoneCompass_updateInterval: 20
