name: PlayerTracker
version: 1.0
main: newamazingpvp.tracker.Tracker
api-version: 1.16
authors: [ NewAmazingPVP ]
commands:
  track:
    description: Track a player's location
    usage: /track <player>
    aliases: [compass]

description: Simple minecraft plugin to track players in the world
